In [1]:
# Import Dependencies
# from splinter import Browser
# from bs4 import BeautifulSoup
# import requests
import pandas as pd
import json
import os

In [2]:
group0_df = pd.read_csv('group_0.csv')
group1_df = pd.read_csv('group_1.csv')
group2_df = pd.read_csv('group_2.csv')
group3_df = pd.read_csv('group_3.csv')
group4_df = pd.read_csv('group_4.csv')
group5_df = pd.read_csv('group_5.csv')
group6_df = pd.read_csv('group_6.csv')
group7_df = pd.read_csv('group_7.csv')

In [3]:
group0_df.head()

,Ticker,Company Name,HQ City,HQ State/Province,HQ Country,ESG Risk Score,ESG Risk Score Level,ESG Risk Score Percentile,Environment Risk Score,Social Risk Score,...,2019 Performance,Market Cap,Exchange,CEO,Logo Image URL,Website URL,Industry,Sector,Company Description,Grouping
0,AZO,AutoZone Inc.,Memphis,Tennessee,United states of america,12,Negligible,3rd percentile,0.0,8.0,...,42.103443,2.560000e+10,New York Stock Exchange,William C. Rhodes,https://financialmodelingprep.com/images-New-j...,http://www.autozone.com,Retail - Apparel & Specialty,Consumer Cyclical,AutoZone Inc is a retailer and distributor of ...,0
1,RAND.AS,Randstad N.V.,Diemen,Noord-holland,Netherlands,12,Negligible,3rd percentile,0.0,9.0,...,35.794462,9.640000e+09,Amsterdam,NaN,https://financialmodelingprep.com/images-New-j...,http://www.randstad.com,Staffing & Employment Services,Industrials,Randstad NV provides solutions in the field of...,0
2,AAP,Advance Auto Parts Inc W/I,Raleigh,North carolina,United states of america,13,Negligible,4th percentile,0.0,9.0,...,1.714721,9.370000e+09,New York Stock Exchange,Thomas R. Greco,https://financialmodelingprep.com/images-New-j...,https://shop.advanceautoparts.com,Retail - Apparel & Specialty,Consumer Cyclical,Advance Auto Parts Inc is an automotive afterm...,0
3,KMX,CarMax Inc,Richmond,Virginia,United states of america,13,Negligible,4th percentile,0.0,9.0,...,39.757692,1.620000e+10,New York Stock Exchange,NaN,https://financialmodelingprep.com/images-New-j...,http://www.carmax.com,Autos,Consumer Cyclical,CarMax Inc is engaged in the automobile dealer...,0
4,MAN,ManpowerGroup,Milwaukee,Wisconsin,United states of america,13,Negligible,4th percentile,0.0,9.0,...,49.845679,5.540000e+09,New York Stock Exchange,Jonas Prising,https://financialmodelingprep.com/images-New-j...,http://www.manpowergroup.com,Employment Services,Industrials,ManpowerGroup Inc is engaged in the employment...,0

In [4]:
group0_df = group0_df[['Ticker','Company Name','2019 Performance']]
group0_df = group0_df.rename(columns={"Company Name": "Company", "2019 Performance": "RoR"})

group1_df = group1_df[['Ticker','Company Name','2019 Performance']]
group1_df = group1_df.rename(columns={"Company Name": "Company", "2019 Performance": "RoR"})

group2_df = group2_df[['Ticker','Company Name','2019 Performance']]
group2_df = group2_df.rename(columns={"Company Name": "Company", "2019 Performance": "RoR"})

group3_df = group3_df[['Ticker','Company Name','2019 Performance']]
group3_df = group3_df.rename(columns={"Company Name": "Company", "2019 Performance": "RoR"})

group4_df = group4_df[['Ticker','Company Name','2019 Performance']]
group4_df = group4_df.rename(columns={"Company Name": "Company", "2019 Performance": "RoR"})

group5_df = group5_df[['Ticker','Company Name','2019 Performance']]
group5_df = group5_df.rename(columns={"Company Name": "Company", "2019 Performance": "RoR"})

group6_df = group6_df[['Ticker','Company Name','2019 Performance']]
group6_df = group6_df.rename(columns={"Company Name": "Company", "2019 Performance": "RoR"})

group7_df = group7_df[['Ticker','Company Name','2019 Performance']]
group7_df = group7_df.rename(columns={"Company Name": "Company", "2019 Performance": "RoR"})

In [5]:
group0_df['RoR'] = group0_df['RoR'].astype(float)
# group0_df["RoR"] = pd.to_numeric(group0_df["RoR"], downcast="float", errors='coerce')
group0_df['RoR'] = pd.Series(["{0:.1f}%".format(val * 1) for val in group0_df['RoR']], index = group0_df.index)
group0_df.head()

    Ticker                     Company    RoR
0      AZO               AutoZone Inc.  42.1%
1  RAND.AS               Randstad N.V.  35.8%
2      AAP  Advance Auto Parts Inc W/I   1.7%
3      KMX                  CarMax Inc  39.8%
4      MAN               ManpowerGroup  49.8%

In [6]:
group1_df['RoR'] = group1_df['RoR'].astype(float)
group1_df['RoR'] = pd.Series(["{0:.1f}%".format(val * 1) for val in group1_df['RoR']], index = group1_df.index)
group2_df['RoR'] = group2_df['RoR'].astype(float)
group2_df['RoR'] = pd.Series(["{0:.1f}%".format(val * 1) for val in group2_df['RoR']], index = group2_df.index)
group3_df['RoR'] = group3_df['RoR'].astype(float)
group3_df['RoR'] = pd.Series(["{0:.1f}%".format(val * 1) for val in group3_df['RoR']], index = group3_df.index)
group4_df['RoR'] = group4_df['RoR'].astype(float)
group4_df['RoR'] = pd.Series(["{0:.1f}%".format(val * 1) for val in group4_df['RoR']], index = group4_df.index)
group5_df['RoR'] = group5_df['RoR'].astype(float)
group5_df['RoR'] = pd.Series(["{0:.1f}%".format(val * 1) for val in group5_df['RoR']], index = group5_df.index)
group6_df['RoR'] = group6_df['RoR'].astype(float)
group6_df['RoR'] = pd.Series(["{0:.1f}%".format(val * 1) for val in group6_df['RoR']], index = group6_df.index)
group7_df['RoR'] = group7_df['RoR'].astype(float)
group7_df['RoR'] = pd.Series(["{0:.1f}%".format(val * 1) for val in group7_df['RoR']], index = group7_df.index)
group7_df.head()

  Ticker                                            Company    RoR
0   CBRE                             CBRE Group Inc Class A  53.1%
1    JLL                    Jones Lang LaSalle Incorporated  37.5%
2   FLEX                                          Flex Ltd.  65.8%
3    TEL  TE Connectivity Ltd. New Switzerland Registere...  26.7%
4    AVT                                         Avnet Inc.  17.6%

In [7]:
group0_top20_df = group0_df.head(20)
group1_top20_df = group1_df.head(20)
group2_top20_df = group2_df.head(20)
group3_top20_df = group3_df.head(20)
group4_top20_df = group4_df.head(20)
group5_top20_df = group5_df.head(20)
group6_top20_df = group6_df.head(20)
group7_top20_df = group7_df.head(20)

In [8]:
# group0_top20_df.set_index('Ticker',inplace=True)
# group0_top20_df

In [9]:
json0 = group0_top20_df.to_json('group0.json',orient='records')
json1 = group1_top20_df.to_json('group1.json',orient='records')
json2 = group2_top20_df.to_json('group2.json',orient='records')
json3 = group3_top20_df.to_json('group3.json',orient='records')
json4 = group4_top20_df.to_json('group4.json',orient='records')
json5 = group5_top20_df.to_json('group5.json',orient='records')
json6 = group6_top20_df.to_json('group6.json',orient='records')
json7 = group7_top20_df.to_json('group7.json',orient='records')

In [10]:
json_print5 = group5_top20_df.to_json(orient='records')

In [11]:
json_print5

'[{"Ticker":"AMGN","Company":"Amgen Inc.","RoR":"23.8%"},{"Ticker":"BIIB","Company":"Biogen Inc.","RoR":"-1.4%"},{"Ticker":"INFO","Company":"IHS Markit Ltd.","RoR":"57.1%"},{"Ticker":"MSCI","Company":"MSCI Inc","RoR":"75.1%"},{"Ticker":"NLSN","Company":"Nielsen N.V.","RoR":"-13.0%"},{"Ticker":"ANTM","Company":"Anthem Inc.","RoR":"15.0%"},{"Ticker":"HUM","Company":"Humana Inc.","RoR":"27.9%"},{"Ticker":"IQV","Company":"IQVIA Holdings Inc.","RoR":"33.0%"},{"Ticker":"SSNC","Company":"SS&C Technologies Holdings Inc.","RoR":"36.1%"},{"Ticker":"ALLY","Company":"Ally Financial Inc.","RoR":"34.9%"},{"Ticker":"REGN","Company":"Regeneron Pharmaceuticals Inc.","RoR":"0.5%"},{"Ticker":"COF","Company":"Capital One Financial Corporation","RoR":"36.1%"},{"Ticker":"VRTX","Company":"Vertex Pharmaceuticals Incorporated","RoR":"32.1%"},{"Ticker":"ALXN","Company":"Alexion Pharmaceuticals Inc.","RoR":"11.1%"},{"Ticker":"BMRN","Company":"BioMarin Pharmaceutical Inc.","RoR":"-0.7%"},{"Ticker":"S","Company":"Sprint Corporation","RoR":"-10.5%"},{"Ticker":"BAC","Company":"Bank of America Corporation","RoR":"42.9%"},{"Ticker":"BMY","Company":"Bristol-Myers Squibb Company","RoR":"23.5%"},{"Ticker":"EFX","Company":"Equifax Inc.","RoR":"50.5%"},{"Ticker":"HCA","Company":"HCA Healthcare Inc.","RoR":"18.8%"}]'

In [14]:
json_print7 = group7_top20_df.to_json(orient='records')
json_print7

'[{"Ticker":"CBRE","Company":"CBRE Group Inc Class A","RoR":"53.1%"},{"Ticker":"JLL","Company":"Jones Lang LaSalle Incorporated","RoR":"37.5%"},{"Ticker":"FLEX","Company":"Flex Ltd.","RoR":"65.8%"},{"Ticker":"TEL","Company":"TE Connectivity Ltd. New Switzerland Registered Shares","RoR":"26.7%"},{"Ticker":"AVT","Company":"Avnet Inc.","RoR":"17.6%"},{"Ticker":"KEYS","Company":"Keysight Technologies Inc.","RoR":"65.3%"},{"Ticker":"PLD","Company":"ProLogis Inc.","RoR":"51.8%"},{"Ticker":"CDW","Company":"CDW Corporation","RoR":"76.2%"},{"Ticker":"CDI.PA","Company":"Christian Dior SE","RoR":"36.8%"},{"Ticker":"GIL.TO","Company":"Gildan Activewear Inc.","RoR":"-7.4%"},{"Ticker":"GIL","Company":"Gildan Activewear Inc. Class A Sub. Vot.","RoR":"-2.7%"},{"Ticker":"RMS.PA","Company":"Hermes International Societe en commandite par actions","RoR":"37.4%"},{"Ticker":"HPQ","Company":"HP Inc.","RoR":"0.4%"},{"Ticker":"MC.PA","Company":"LVMH Moet Hennessy - Louis Vuitton, Societe Europeenne","RoR":"60.4%"},{"Ticker":"POW.TO","Company":"Power Corporation of Canada","RoR":"36.4%"},{"Ticker":"REG","Company":"Regency Centers Corporation","RoR":"7.5%"},{"Ticker":"RHI","Company":"Robert Half International Inc.","RoR":"10.4%"},{"Ticker":"APD","Company":"Air Products and Chemicals Inc.","RoR":"46.8%"},{"Ticker":"BBY","Company":"Best Buy Co. Inc.","RoR":"65.8%"},{"Ticker":"COV.PA","Company":"Covivio","RoR":"20.2%"}]'